// data.js — Static world definitions for Simple Motor Racing
// All stats are 0–100 unless otherwise noted.
// Higher is always better (e.g. high reliability = fewer failures, high power = faster).
//
// NOTE: Team chassis stats (aero, chassisReliability, pitCrewRating, setupAbility, fuelCapacity)
// are S1 baseline values. worldstate.js overrides them with era-seeded values for each season.

// ─── Engine Manufacturers ─────────────────────────────────────────────────────
// power:       straight-line speed advantage; dominant factor on power sectors
// reliability: inverse of failure probability; lower = more likely to break
// fuelBurnRate: multiplier on circuit baseFuelBurnPerLap; 1.0 = baseline
//
// These are S1 baseline stats; worldstate.js regenerates them each engine era (every 3 seasons).

export const ENGINES = {
  ferrosso:    { id: 'ferrosso',    name: 'Ferrosso',    power: 82, reliability: 72, fuelBurnRate: 1.12 },
  sakura:      { id: 'sakura',      name: 'Sakura',      power: 79, reliability: 78, fuelBurnRate: 1.05 },
  kaiserwerke: { id: 'kaiserwerke', name: 'Kaiserwerke', power: 84, reliability: 70, fuelBurnRate: 1.15 },
  lanchester:  { id: 'lanchester',  name: 'Lanchester',  power: 70, reliability: 85, fuelBurnRate: 1.02 },
  sterling:    { id: 'sterling',    name: 'Sterling',    power: 72, reliability: 88, fuelBurnRate: 1.00 },
  henry:       { id: 'henry',       name: 'Henry',       power: 68, reliability: 90, fuelBurnRate: 0.98 },
  watt:        { id: 'watt',        name: 'Watt',        power: 75, reliability: 82, fuelBurnRate: 1.05 },
  barsanti:    { id: 'barsanti',    name: 'Barsanti',    power: 76, reliability: 75, fuelBurnRate: 1.08 },
  mirabeau:    { id: 'mirabeau',    name: 'Mirabeau',    power: 78, reliability: 80, fuelBurnRate: 1.10 },
  tannhauser:  { id: 'tannhauser',  name: 'Tannhäuser',  power: 80, reliability: 74, fuelBurnRate: 1.12 },
  eclipse:     { id: 'eclipse',     name: 'Éclipse',     power: 77, reliability: 78, fuelBurnRate: 1.06 },
  kosen:       { id: 'kosen',       name: 'Kosen',       power: 73, reliability: 83, fuelBurnRate: 1.03 },
  titan:       { id: 'titan',       name: 'Titan',       power: 71, reliability: 86, fuelBurnRate: 1.00 },
  valkyr:      { id: 'valkyr',      name: 'Valkyr',      power: 74, reliability: 79, fuelBurnRate: 1.07 },
};

// ─── Tyre Manufacturers ───────────────────────────────────────────────────────
// maxGrip: peak grip level at zero wear (0–100)
// wearRate: base degradation per sector tick before compound/aggression/abrasion scaling
// letter:   single-letter code shown on timing sheet
//
// These are S1 baseline stats; worldstate.js regenerates them each tyre era (every 2 seasons).

export const TYRES = {
  blackstripe: { id: 'blackstripe', name: 'Blackstripe', letter: 'B', maxGrip: 88, wearRate: 0.0112 },
  vulcan:      { id: 'vulcan',      name: 'Vulcan',      letter: 'V', maxGrip: 86, wearRate: 0.0128 },
  saltwell:    { id: 'saltwell',    name: 'Saltwell',     letter: 'S', maxGrip: 84, wearRate: 0.0118 },
};

// Backward-compat alias
export const TYRE_MANUFACTURERS = TYRES;

// ─── Tyre Compounds ───────────────────────────────────────────────────────────
// wearMultiplier: scales the tyre manufacturer's baseWearRate each sector
// gripModifier:   added to tyre manufacturer's maxGrip (0–100 scale) before normalising

export const COMPOUNDS = {
  soft: {
    wearMultiplier: 1.40,
    gripModifier:   10,
  },
  medium: {
    wearMultiplier: 0.85,  // more durable — covers 20–30 lap closing stints
    gripModifier:    0,
  },
  hard: {
    wearMultiplier: 0.50,  // ~2.8× longer than soft; justifies 1% fresh pace deficit
    gripModifier:   -8,    // ~1% slower fresh (was -30 → ~2.4% — too harsh)
  },
};

// ─── Teams ────────────────────────────────────────────────────────────────────
// isWorks:       true if this team builds its own engine (always uses worksEngineId)
// worksEngineId: engine id for works teams; null for customer (garagiste) teams
// baseNumbers:   [lead, second] — permanent race numbers; champion's team gets [1,2] instead
// fundingLevel:  0–100; controls speed of season-end chassis development
// aero, chassisReliability, pitCrewRating, setupAbility, fuelCapacity: all seeded dynamically by worldstate.js
// strategy:      static personality — how the team makes pit decisions

export const TEAMS = [
  {
    id:                 'hartwell',
    name:               'Team Hartwell Racing',
    shortName:          'Hartwell',
    nationality:        'British',
    spriteRow:          0, spriteCol: 0,
    colour:             '#127517',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [5, 6],
    fundingLevel:       90,
    aero:               78,
    chassisReliability: 85,
    pitCrewRating:      84,
    setupAbility:       82,
    strategy: {
      wearTrigger:    0.80,
      fuelTrigger:    7,
      fuelMarginLaps: 2,
      tyreLifeModel:  'fuelCorrected',
    },
  },
  {
    id:                 'frd',
    name:               'Flinders Racing Developments',
    shortName:          'FRD',
    nationality:        'Australian',
    spriteRow:          0, spriteCol: 1,
    colour:             '#c69753',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [19, 20],
    fundingLevel:       55,
    aero:               52,
    chassisReliability: 75,
    pitCrewRating:      62,
    setupAbility:       58,
    strategy: {
      wearTrigger:    0.78,
      fuelTrigger:    8,
      fuelMarginLaps: 3,
      tyreLifeModel:  'basic',
    },
  },
  {
    id:                 'ferrosso',
    name:               'Officine Ferrosso',
    shortName:          'Ferrosso',
    nationality:        'Italian',
    spriteRow:          0, spriteCol: 2,
    colour:             '#fe3029',
    isWorks:            true,
    worksEngineId:      'ferrosso',
    baseNumbers:        [27, 28],
    fundingLevel:       88,
    aero:               82,
    chassisReliability: 72,
    pitCrewRating:      78,
    setupAbility:       88,
    strategy: {
      wearTrigger:    0.82,
      fuelTrigger:    6,
      fuelMarginLaps: 2,
      tyreLifeModel:  'fuelCorrected',
    },
  },
  {
    id:                 'vettura',
    name:               'Vettura Corse',
    shortName:          'Vettura',
    nationality:        'Italian',
    spriteRow:          0, spriteCol: 3,
    colour:             '#f6e923',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [11, 12],
    fundingLevel:       62,
    aero:               60,
    chassisReliability: 78,
    pitCrewRating:      68,
    setupAbility:       65,
    strategy: {
      wearTrigger:    0.77,
      fuelTrigger:    7,
      fuelMarginLaps: 3,
      tyreLifeModel:  'basic',
    },
  },
  {
    id:                 'kaiserwerke',
    name:               'Kaiserwerke GP',
    shortName:          'Kaiserwerke',
    nationality:        'German',
    spriteRow:          1, spriteCol: 0,
    colour:             '#f2f2f2',
    isWorks:            true,
    worksEngineId:      'kaiserwerke',
    baseNumbers:        [9, 10],
    fundingLevel:       90,
    aero:               78,
    chassisReliability: 70,
    pitCrewRating:      82,
    setupAbility:       85,
    strategy: {
      wearTrigger:    0.83,
      fuelTrigger:    6,
      fuelMarginLaps: 2,
      tyreLifeModel:  'fuelCorrected',
    },
  },
  {
    id:                 'mistral',
    name:               'Écurie Mistral',
    shortName:          'Mistral',
    nationality:        'French',
    spriteRow:          1, spriteCol: 1,
    colour:             '#397ee0',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [3, 4],
    fundingLevel:       68,
    aero:               72,
    chassisReliability: 80,
    pitCrewRating:      76,
    setupAbility:       70,
    strategy: {
      wearTrigger:    0.80,
      fuelTrigger:    7,
      fuelMarginLaps: 2,
      tyreLifeModel:  'fuelCorrected',
    },
  },
  {
    id:                 'alpenring',
    name:               'Alpenring Motorsport',
    shortName:          'Alpenring',
    nationality:        'Austrian',
    spriteRow:          1, spriteCol: 2,
    colour:             '#b5b5b5',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [21, 22],
    fundingLevel:       48,
    aero:               50,
    chassisReliability: 82,
    pitCrewRating:      60,
    setupAbility:       55,
    strategy: {
      wearTrigger:    0.76,
      fuelTrigger:    8,
      fuelMarginLaps: 3,
      tyreLifeModel:  'basic',
    },
  },
  {
    id:                 'deltaBravo',
    name:               'Delta Bravo Racing',
    shortName:          'Delta Bravo',
    carImageId:         'dbr',
    nationality:        'British',
    spriteRow:          1, spriteCol: 3,
    colour:             '#fb8d1f',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [7, 8],
    fundingLevel:       65,
    aero:               62,
    chassisReliability: 76,
    pitCrewRating:      70,
    setupAbility:       68,
    strategy: {
      wearTrigger:    0.79,
      fuelTrigger:    7,
      fuelMarginLaps: 3,
      tyreLifeModel:  'basic',
    },
  },
  {
    id:                 'eaglecrest',
    name:               'Eaglecrest Racing',
    shortName:          'Eaglecrest',
    nationality:        'American',
    spriteRow:          2, spriteCol: 0,
    colour:             '#5ae5e2',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [15, 16],
    fundingLevel:       70,
    aero:               65,
    chassisReliability: 84,
    pitCrewRating:      72,
    setupAbility:       70,
    strategy: {
      wearTrigger:    0.80,
      fuelTrigger:    7,
      fuelMarginLaps: 2,
      tyreLifeModel:  'fuelCorrected',
    },
  },
  {
    id:                 'sakura',
    name:               'Sakura Grand Prix',
    shortName:          'Sakura',
    nationality:        'Japanese',
    spriteRow:          2, spriteCol: 1,
    colour:             '#fe9aea',
    isWorks:            true,
    worksEngineId:      'sakura',
    baseNumbers:        [17, 18],
    fundingLevel:       72,
    aero:               75,
    chassisReliability: 75,
    pitCrewRating:      80,
    setupAbility:       74,
    strategy: {
      wearTrigger:    0.82,
      fuelTrigger:    6,
      fuelMarginLaps: 2,
      tyreLifeModel:  'fuelCorrected',
    },
  },
  {
    id:                 'santos',
    name:               'Santos Automotive',
    shortName:          'Santos',
    nationality:        'Brazilian',
    spriteRow:          2, spriteCol: 2,
    colour:             '#9e191c',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [23, 24],
    fundingLevel:       40,
    aero:               40,
    chassisReliability: 65,
    pitCrewRating:      48,
    setupAbility:       38,
    strategy: {
      wearTrigger:    0.75,
      fuelTrigger:    9,
      fuelMarginLaps: 4,
      tyreLifeModel:  'basic',
    },
  },
  {
    id:                 'oconnell',
    name:               "O'Connell Racing",
    shortName:          "O'Connell",
    nationality:        'Irish',
    spriteRow:          2, spriteCol: 3,
    colour:             '#10eb25',
    isWorks:            false,
    worksEngineId:      null,
    baseNumbers:        [25, 26],
    fundingLevel:       40,
    aero:               38,
    chassisReliability: 64,
    pitCrewRating:      44,
    setupAbility:       35,
    strategy: {
      wearTrigger:    0.75,
      fuelTrigger:    9,
      fuelMarginLaps: 4,
      tyreLifeModel:  'basic',
    },
  },
];

// ─── Circuits ─────────────────────────────────────────────────────────────────
// Note: fuelCapacity is NOT on the circuit — it lives on each team (worldstate.js).
// baseFuelBurnPerLap: kg/lap at fuelBurnRate 1.0; longer/faster circuits burn more.
// trackAbrasiveness: 0.0 (smooth) → 1.0 (very rough); scales tyre wear per sector.
// overtakingDifficulty: multiplier on base overtake probability. 0.50 = very hard (street/tight), 1.0 = neutral, 1.45 = easy (airfield/open).
// pitLaneTime: seconds to traverse the pit lane (added to every stop).
// baseTyreChangeTime: seconds for a tyre change at pitCrewRating 100; scales with crew rating.
// fuelRigRate: seconds per kg of fuel added.

export const CIRCUITS = {

  hawkesbury: {
    id:                 'hawkesbury',
    name:               'Hawkesbury River Circuit',
    country:            'Australia',
    location:           'Windsor, New South Wales',
    type:               'Parkland / public road',
    character:          'Fast, riverside, narrow',
    profile:            'Public road circuit following the river bends north-west of Sydney. The flood-plain straight allows very high speeds before a tight riverside chicane. A classic antipodean character — fast, narrow, and unforgiving.',
    eventName:          'Australian Grand Prix',
    lengthKm:           6.1,
    totalLaps:          49,
    trackAbrasiveness:  0.30,
    overtakingDifficulty: 0.70,
    baseFuelBurnPerLap: 1.70,
    pitLaneTime:        22,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Riverside bends',     powerWeight: 0.03, aeroWeight: 0.05, wearWeight: 1.30, fuelWeight: 0.80, baseSectorTime: 42.0 },
      { id: 2, label: 'Floodplain straight',  powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.70, fuelWeight: 1.40, baseSectorTime: 48.0 },
      { id: 3, label: 'Chicane sequence',     powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.80, baseSectorTime: 38.0 },
    ],
  },

  marlborough: {
    id:                 'marlborough',
    name:               'Marlborough Sounds Circuit',
    country:            'New Zealand',
    location:           'Picton',
    type:               'Parkland / public road',
    character:          'Fast, hillside, coastal',
    profile:            'Clifftop road circuit above the Marlborough Sounds. Breathtaking scenery throughout; narrow sections with essentially no runoff. The remoteness of the venue is a point of national pride rather than a deterrent.',
    eventName:          'New Zealand Grand Prix',
    lengthKm:           5.8,
    totalLaps:          52,
    trackAbrasiveness:  0.32,
    overtakingDifficulty: 0.75,
    baseFuelBurnPerLap: 1.62,
    pitLaneTime:        21,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Clifftop sweeps',      powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.85, baseSectorTime: 40.0 },
      { id: 2, label: 'Descent section',       powerWeight: 0.05, aeroWeight: 0.02, wearWeight: 0.80, fuelWeight: 1.35, baseSectorTime: 44.0 },
      { id: 3, label: 'Hairpin loop',          powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.25, fuelWeight: 0.80, baseSectorTime: 36.0 },
    ],
  },

  pampa: {
    id:                 'pampa',
    name:               'Circuito de la Pampa',
    country:            'Argentina',
    location:           'Córdoba',
    type:               'Purpose-built',
    character:          'Very fast, flat, windy',
    profile:            'Open plains circuit on the pampas outside Córdoba. The pampero wind makes handling treacherous and unpredictable. A distinctly Argentine identity — vast, exposed, and relentless.',
    eventName:          'Gran Premio de Argentina',
    lengthKm:           5.8,
    totalLaps:          52,
    trackAbrasiveness:  0.22,
    overtakingDifficulty: 1.35,
    baseFuelBurnPerLap: 1.65,
    pitLaneTime:        20,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Approach straight',    powerWeight: 0.05, aeroWeight: 0.02, wearWeight: 0.75, fuelWeight: 1.35, baseSectorTime: 42.0 },
      { id: 2, label: 'Back straight',         powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.70, fuelWeight: 1.45, baseSectorTime: 46.0 },
      { id: 3, label: 'Final sweeper',          powerWeight: 0.02, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.80, baseSectorTime: 34.0 },
    ],
  },

  guadalajara: {
    id:                 'guadalajara',
    name:               'Autodromo de Guadalajara',
    country:            'Mexico',
    location:           'Guadalajara',
    type:               'Purpose-built',
    character:          'Medium speed, technical, hot',
    profile:            "Guadalajara's purpose-built circuit combines a tight technical stadium section with a long sweeping right-hander. Intense heat and altitude are defining factors. The race is a point of fierce civic pride in Mexico's second city.",
    eventName:          'Gran Premio de México',
    lengthKm:           4.8,
    totalLaps:          63,
    trackAbrasiveness:  0.38,
    overtakingDifficulty: 0.70,
    baseFuelBurnPerLap: 1.35,
    pitLaneTime:        20,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Stadium section',       powerWeight: 0.03, aeroWeight: 0.05, wearWeight: 1.35, fuelWeight: 0.75, baseSectorTime: 32.0 },
      { id: 2, label: 'Long sweeper',          powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 0.90, fuelWeight: 1.15, baseSectorTime: 38.0 },
      { id: 3, label: 'Technical infield',     powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.35, fuelWeight: 0.75, baseSectorTime: 28.0 },
    ],
  },

  kyushu: {
    id:                 'kyushu',
    name:               'Kyushu Motorsport Park',
    country:            'Japan',
    location:           'Kumamoto',
    type:               'Purpose-built',
    character:          'Technical, hillside, tight infield',
    profile:            'Built into the foothills of the Aso volcanic region. Abrupt changes in gradient punish set-up compromises. The smoking caldera of Mount Aso is visible from the top of the circuit on clear days.',
    eventName:          'Japanese Grand Prix',
    lengthKm:           4.4,
    totalLaps:          68,
    trackAbrasiveness:  0.30,
    overtakingDifficulty: 0.60,
    baseFuelBurnPerLap: 1.25,
    pitLaneTime:        20,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Hillside section',      powerWeight: 0.03, aeroWeight: 0.05, wearWeight: 1.30, fuelWeight: 0.80, baseSectorTime: 30.0 },
      { id: 2, label: 'Technical complex',     powerWeight: 0.02, aeroWeight: 0.06, wearWeight: 1.40, fuelWeight: 0.70, baseSectorTime: 28.0 },
      { id: 3, label: 'Back straight',         powerWeight: 0.05, aeroWeight: 0.01, wearWeight: 0.80, fuelWeight: 1.35, baseSectorTime: 35.0 },
    ],
  },

  nairobi: {
    id:                 'nairobi',
    name:               'East African Grand Prix Circuit',
    country:            'Kenya',
    location:           'Nairobi',
    type:               'Purpose-built',
    character:          'Medium speed, balanced, high altitude',
    profile:            "Kenya's purpose-built circuit sits at high altitude on the outskirts of Nairobi, where the thin air significantly affects engine performance and driver endurance. The East African Grand Prix is the oldest race on the African continent.",
    eventName:          'East African Grand Prix',
    lengthKm:           5.1,
    totalLaps:          59,
    trackAbrasiveness:  0.28,
    overtakingDifficulty: 1.00,
    baseFuelBurnPerLap: 1.42,
    pitLaneTime:        21,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Fast approach',         powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 0.90, fuelWeight: 1.20, baseSectorTime: 36.0 },
      { id: 2, label: 'Technical complex',     powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.30, fuelWeight: 0.80, baseSectorTime: 32.0 },
      { id: 3, label: 'Back straight',         powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.75, fuelWeight: 1.35, baseSectorTime: 38.0 },
    ],
  },

  laeken: {
    id:                 'laeken',
    name:               'Circuit de Bruxelles-Laeken',
    country:            'Belgium',
    location:           'Brussels',
    type:               'Parkland / estate road',
    character:          'Medium speed, park roads, cobblestone',
    profile:            'The Belgian Grand Prix uses the perimeter roads of the royal estate parkland at Laeken. A cobblestone hairpin section adds texture and danger in the wet. One of the traditional curtain-raisers of the European season.',
    eventName:          'Grand Prix de Belgique',
    lengthKm:           5.2,
    totalLaps:          58,
    trackAbrasiveness:  0.45,
    overtakingDifficulty: 0.75,
    baseFuelBurnPerLap: 1.45,
    pitLaneTime:        22,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Parkland section',      powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.85, baseSectorTime: 36.0 },
      { id: 2, label: 'Cobblestone stretch',   powerWeight: 0.05, aeroWeight: 0.02, wearWeight: 1.50, fuelWeight: 1.10, baseSectorTime: 42.0 },
      { id: 3, label: 'Hairpin loop',          powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.35, fuelWeight: 0.75, baseSectorTime: 30.0 },
    ],
  },

  cotedazur: {
    id:                 'cotedazur',
    name:               "Circuit de la Côte d'Azur",
    country:            'France',
    location:           'Nice',
    type:               'Street',
    character:          'Fast, narrow, seafront',
    profile:            "The Promenade des Anglais forms the thunderous main straight; a tight old-town hairpin brings drivers back through the narrow streets of Nice. The harbour glitters throughout. The jewel of the European season.",
    eventName:          "Grand Prix de la Côte d'Azur",
    lengthKm:           3.1,
    totalLaps:          78,
    trackAbrasiveness:  0.40,
    overtakingDifficulty: 0.55,
    baseFuelBurnPerLap: 0.92,
    pitLaneTime:        19,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Promenade straight',    powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.70, fuelWeight: 1.45, baseSectorTime: 24.0 },
      { id: 2, label: 'Old-town hairpin',      powerWeight: 0.02, aeroWeight: 0.06, wearWeight: 1.45, fuelWeight: 0.70, baseSectorTime: 22.0 },
      { id: 3, label: 'Return streets',        powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.15, fuelWeight: 0.85, baseSectorTime: 22.0 },
    ],
  },

  palermo: {
    id:                 'palermo',
    name:               'Autodromo di Palermo',
    country:            'Italy',
    location:           'Palermo, Sicily',
    type:               'Purpose-built',
    character:          'Technical, tight, Mediterranean heat',
    profile:            "A hillside circuit carved above the Conca d'Oro valley outside Palermo. Tricky gradient changes throughout; the Mediterranean heat builds through the afternoon. Sicily's own grand prix, fiercely independent of the mainland.",
    eventName:          'Gran Premio di Sicilia',
    lengthKm:           4.2,
    totalLaps:          71,
    trackAbrasiveness:  0.42,
    overtakingDifficulty: 0.65,
    baseFuelBurnPerLap: 1.20,
    pitLaneTime:        20,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Hillside complex',      powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.40, fuelWeight: 0.75, baseSectorTime: 30.0 },
      { id: 2, label: 'Descent section',       powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 0.95, fuelWeight: 1.15, baseSectorTime: 33.0 },
      { id: 3, label: 'Tight final',           powerWeight: 0.02, aeroWeight: 0.06, wearWeight: 1.45, fuelWeight: 0.70, baseSectorTime: 27.0 },
    ],
  },

  schwarzwald: {
    id:                 'schwarzwald',
    name:               'Schwarzwald-Ring',
    country:            'Germany',
    location:           'Freiburg im Breisgau',
    type:               'Parkland / forest road',
    character:          'Fast, sweeping, forest',
    profile:            "Long downhill sections plunge through Black Forest pine on the Schwarzwald-Ring. One notorious blind crest — known as der Sprung — has defined the circuit's reputation since its earliest days. The spiritual home of German motor racing.",
    eventName:          'Großer Preis von Deutschland',
    lengthKm:           7.1,
    totalLaps:          42,
    trackAbrasiveness:  0.28,
    overtakingDifficulty: 1.15,
    baseFuelBurnPerLap: 1.98,
    pitLaneTime:        22,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Forest descent',        powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 1.00, fuelWeight: 1.10, baseSectorTime: 50.0 },
      { id: 2, label: 'Der Sprung section',    powerWeight: 0.06, aeroWeight: 0.02, wearWeight: 0.75, fuelWeight: 1.40, baseSectorTime: 56.0 },
      { id: 3, label: 'Return sweep',          powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.80, baseSectorTime: 42.0 },
    ],
  },

  karlovyvary: {
    id:                 'karlovyvary',
    name:               'Karlovy Vary Kurkurs',
    country:            'Czechoslovakia',
    location:           'Karlovy Vary',
    type:               'Parkland / public road',
    character:          'Fast, sweeping, forested valley',
    profile:            'The Karlovy Vary Kurkurs follows the wooded banks of the Ohře river before climbing through the spa district and onto a fast hillside loop above the valley. Speeds on the riverside section are among the highest on the European calendar. The grandstands fill with the cream of central European society.',
    eventName:          'Velka cena Ceskoslovenska',
    lengthKm:           7.4,
    totalLaps:          41,
    trackAbrasiveness:  0.26,
    overtakingDifficulty: 1.20,
    baseFuelBurnPerLap: 2.05,
    pitLaneTime:        23,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Riverside section',     powerWeight: 0.05, aeroWeight: 0.02, wearWeight: 0.80, fuelWeight: 1.35, baseSectorTime: 50.0 },
      { id: 2, label: 'Spa district',          powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 0.95, fuelWeight: 1.10, baseSectorTime: 60.0 },
      { id: 3, label: 'Hillside loop',         powerWeight: 0.04, aeroWeight: 0.04, wearWeight: 1.10, fuelWeight: 0.95, baseSectorTime: 42.0 },
    ],
  },

  brookthorpe: {
    id:                 'brookthorpe',
    name:               'Brookthorpe Park Circuit',
    country:            'England',
    location:           'Gloucestershire',
    type:               'Airfield',
    character:          'Flat, fast, exposed',
    profile:            'Built on a wartime airfield perimeter in the Gloucestershire countryside. Absolutely flat and very fast; the notorious crosswinds off the Severn Vale are an invisible but constant factor. Raw, functional, and unmistakably British.',
    eventName:          'British Grand Prix',
    lengthKm:           3.3,
    totalLaps:          78,
    trackAbrasiveness:  0.45,
    overtakingDifficulty: 1.45,
    baseFuelBurnPerLap: 0.98,
    pitLaneTime:        18,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Main straight',         powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.65, fuelWeight: 1.50, baseSectorTime: 25.0 },
      { id: 2, label: 'Back straight',         powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.70, fuelWeight: 1.45, baseSectorTime: 26.0 },
      { id: 3, label: 'Infield section',       powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.55, fuelWeight: 0.70, baseSectorTime: 23.0 },
    ],
  },

  hamnkurs: {
    id:                 'hamnkurs',
    name:               'Göteborg Hamnkurs',
    country:            'Sweden',
    location:           'Gothenburg',
    type:               'Street',
    character:          'Medium speed, harbourfront, flat',
    profile:            'A dockside street circuit through the Lindholmen and Frihamnen districts of Gothenburg. Tram tracks sealed under the tarmac remain faintly visible and still catch drivers in the wet. Compact but with a genuine overtaking opportunity at the harbour bend.',
    eventName:          'Svenska Grand Prix',
    lengthKm:           3.9,
    totalLaps:          77,
    trackAbrasiveness:  0.38,
    overtakingDifficulty: 0.90,
    baseFuelBurnPerLap: 1.12,
    pitLaneTime:        19,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Harbour straight',      powerWeight: 0.05, aeroWeight: 0.02, wearWeight: 0.80, fuelWeight: 1.35, baseSectorTime: 28.0 },
      { id: 2, label: 'Dockside section',      powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.85, baseSectorTime: 30.0 },
      { id: 3, label: 'Tram district',         powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.40, fuelWeight: 0.75, baseSectorTime: 30.0 },
    ],
  },

  rovaniemi: {
    id:                 'rovaniemi',
    name:               'Rovaniemi Arctic Circuit',
    country:            'Finland',
    location:           'Rovaniemi',
    type:               'Purpose-built',
    character:          'Flat, fast, extreme cold, remote',
    profile:            'Just south of the Arctic Circle, Rovaniemi hosts the most remote race on the calendar. Permafrost makes resurfacing near-impossible, giving the surface a permanently bumpy character that no set-up can fully tame. Perpetual daylight during summer race weekends adds to the disorienting atmosphere.',
    eventName:          'Suomen Grand Prix',
    lengthKm:           4.7,
    totalLaps:          64,
    trackAbrasiveness:  0.50,
    overtakingDifficulty: 1.25,
    baseFuelBurnPerLap: 1.32,
    pitLaneTime:        20,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Long straight',         powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.75, fuelWeight: 1.45, baseSectorTime: 34.0 },
      { id: 2, label: 'Back section',          powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 1.00, fuelWeight: 1.10, baseSectorTime: 38.0 },
      { id: 3, label: 'Technical complex',     powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.40, fuelWeight: 0.70, baseSectorTime: 30.0 },
    ],
  },

  harbourfront: {
    id:                 'harbourfront',
    name:               'Central Harbourfront Circuit',
    country:            'Hong Kong',
    location:           'Central & Wan Chai',
    type:               'Street',
    character:          'Tight, glamorous, low-speed technical',
    profile:            'Colonial waterfront streets wind through Central and Wan Chai with the harbour always visible from the cockpit. Tram tracks sealed beneath the tarmac catch drivers in the wet. The most prestigious race outside Europe — the post-European season showpiece.',
    eventName:          'Hong Kong Grand Prix',
    lengthKm:           3.2,
    totalLaps:          75,
    trackAbrasiveness:  0.40,
    overtakingDifficulty: 0.50,
    baseFuelBurnPerLap: 0.95,
    pitLaneTime:        19,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Waterfront section',    powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.10, fuelWeight: 0.85, baseSectorTime: 22.0 },
      { id: 2, label: 'Tram district',         powerWeight: 0.02, aeroWeight: 0.06, wearWeight: 1.50, fuelWeight: 0.70, baseSectorTime: 24.0 },
      { id: 3, label: 'Wan Chai chicane',      powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.40, fuelWeight: 0.70, baseSectorTime: 24.0 },
    ],
  },

  lacMeech: {
    id:                 'lacMeech',
    name:               'Circuit du Lac Meech',
    country:            'Canada',
    location:           'Gatineau, Quebec',
    type:               'Parkland / public road',
    character:          'Medium speed, forested, scenic',
    profile:            "A national park perimeter road circuit in the Quebec lakeland, surrounded by dense boreal forest. Grip levels shift dramatically with the weather. Quebec's French heritage gives the Canadian Grand Prix a distinctly European atmosphere in a North American wilderness.",
    eventName:          'Grand Prix du Canada',
    lengthKm:           5.5,
    totalLaps:          55,
    trackAbrasiveness:  0.30,
    overtakingDifficulty: 0.80,
    baseFuelBurnPerLap: 1.52,
    pitLaneTime:        21,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Lakeside roads',        powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.15, fuelWeight: 0.85, baseSectorTime: 38.0 },
      { id: 2, label: 'Forest straight',       powerWeight: 0.06, aeroWeight: 0.02, wearWeight: 0.75, fuelWeight: 1.40, baseSectorTime: 44.0 },
      { id: 3, label: 'Return section',        powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.80, baseSectorTime: 34.0 },
    ],
  },

  douglas: {
    id:                 'douglas',
    name:               'Douglas Circuit',
    country:            'United States',
    location:           'Roseburg, Oregon',
    type:               'Purpose-built',
    character:          'Fast, sweeping, damp surface, high tyre wear',
    profile:            'Carved through old-growth timber on the western Cascade foothills outside Roseburg, the Douglas Circuit runs across sealed volcanic aggregate that stays permanently damp beneath the forest canopy — even in midsummer the tarmac rarely dries completely, and the green-tinged surface at the forest\'s edge has a treacherous reputation. Tyre wear is the defining story: the abrasive surface destroys rubber faster than almost anywhere on the calendar, and strategies built around softer compounds almost always unravel in the closing stages. The surrounding timber towns send large, raucous crowds; the American Grand Prix draws a different audience from the European parkland races — louder, closer to the barriers, and less forgiving of a poor result.',
    eventName:          'American Grand Prix',
    lengthKm:           5.2,
    totalLaps:          62,
    trackAbrasiveness:  0.60,
    overtakingDifficulty: 1.10,
    baseFuelBurnPerLap: 1.05,
    pitLaneTime:        22,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Forest approach',       powerWeight: 0.04, aeroWeight: 0.04, wearWeight: 1.30, fuelWeight: 0.90, baseSectorTime: 32.0 },
      { id: 2, label: 'Timber straight',       powerWeight: 0.07, aeroWeight: 0.02, wearWeight: 1.00, fuelWeight: 1.35, baseSectorTime: 38.0 },
      { id: 3, label: 'Cascade loop',          powerWeight: 0.02, aeroWeight: 0.06, wearWeight: 1.55, fuelWeight: 0.75, baseSectorTime: 28.0 },
    ],
  },

  lahore: {
    id:                 'lahore',
    name:               'Lahore Street Circuit',
    country:            'Pakistan',
    location:           'Lahore',
    type:               'Street',
    character:          'Slow, technical, cultural',
    profile:            'The colonial-era government quarter and the approach roads to the Shalimar Gardens form a tight and technical street circuit through the heart of Lahore. Intense crowd atmosphere; the Punjab Grand Prix is one of the most culturally vivid events on the calendar.',
    eventName:          'Punjab Grand Prix',
    lengthKm:           3.7,
    totalLaps:          75,
    trackAbrasiveness:  0.35,
    overtakingDifficulty: 0.55,
    baseFuelBurnPerLap: 1.08,
    pitLaneTime:        20,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Government quarter',    powerWeight: 0.02, aeroWeight: 0.05, wearWeight: 1.35, fuelWeight: 0.75, baseSectorTime: 26.0 },
      { id: 2, label: 'Shalimar approach',     powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 1.10, fuelWeight: 0.95, baseSectorTime: 28.0 },
      { id: 3, label: 'Park gates',            powerWeight: 0.02, aeroWeight: 0.06, wearWeight: 1.45, fuelWeight: 0.70, baseSectorTime: 26.0 },
    ],
  },

  recife: {
    id:                 'recife',
    name:               'Circuito do Recife Costeiro',
    country:            'Brazil',
    location:           'Recife',
    type:               'Street',
    character:          'Slow, technical, humid',
    profile:            "Harbourfront and historic centre streets wind through the coastal city of Recife in Brazil's tropical north-east. Extreme heat and humidity are defining factors from the first session. The Brazilian Grand Prix in its most raw and elemental form.",
    eventName:          'Grande Prêmio do Brasil',
    lengthKm:           3.8,
    totalLaps:          72,
    trackAbrasiveness:  0.40,
    overtakingDifficulty: 0.55,
    baseFuelBurnPerLap: 1.10,
    pitLaneTime:        20,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Harbour streets',       powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.85, baseSectorTime: 26.0 },
      { id: 2, label: 'Historic centre',       powerWeight: 0.02, aeroWeight: 0.06, wearWeight: 1.50, fuelWeight: 0.70, baseSectorTime: 28.0 },
      { id: 3, label: 'Coastal return',        powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 1.10, fuelWeight: 0.95, baseSectorTime: 28.0 },
    ],
  },

  bushveld: {
    id:                 'bushveld',
    name:               'Bushveld Grand Prix Circuit',
    country:            'South Africa',
    location:           'Pretoria',
    type:               'Purpose-built',
    character:          'Fast, open, wildlife reserve',
    profile:            "A fast and open purpose-built circuit north of Pretoria, set within a game reserve. The surrounding bushveld is a constant presence at the circuit's edge. The season finale — championships are often settled here under the wide South African sky.",
    eventName:          'South African Grand Prix',
    lengthKm:           5.7,
    totalLaps:          53,
    trackAbrasiveness:  0.25,
    overtakingDifficulty: 1.40,
    baseFuelBurnPerLap: 1.58,
    pitLaneTime:        21,
    baseTyreChangeTime: 6,
    fuelRigRate:        0.12,
    sectors: [
      { id: 1, label: 'Main straight',         powerWeight: 0.06, aeroWeight: 0.01, wearWeight: 0.70, fuelWeight: 1.45, baseSectorTime: 44.0 },
      { id: 2, label: 'Back section',          powerWeight: 0.04, aeroWeight: 0.03, wearWeight: 0.90, fuelWeight: 1.15, baseSectorTime: 44.0 },
      { id: 3, label: 'Return complex',        powerWeight: 0.03, aeroWeight: 0.04, wearWeight: 1.20, fuelWeight: 0.80, baseSectorTime: 38.0 },
    ],
  },
};

// Backward-compat alias — first circuit in the season schedule
export const CIRCUIT = CIRCUITS.hawkesbury;

// ─── Season Schedule ──────────────────────────────────────────────────────────
// 20 rounds × 2 events (qualifying + race) = 40 entries.
// Qualifying and race share the same real-world day (see championship.js).
// eventType distinguishes qualifying (typeFlag=0) from race (typeFlag=1) for seeding.

export const SEASON_SCHEDULE = [
  { round:  1, eventType: 'qualifying', circuitId: 'hawkesbury'      },
  { round:  1, eventType: 'race',       circuitId: 'hawkesbury'      },
  { round:  2, eventType: 'qualifying', circuitId: 'marlborough'     },
  { round:  2, eventType: 'race',       circuitId: 'marlborough'     },
  { round:  3, eventType: 'qualifying', circuitId: 'pampa'           },
  { round:  3, eventType: 'race',       circuitId: 'pampa'           },
  { round:  4, eventType: 'qualifying', circuitId: 'guadalajara'     },
  { round:  4, eventType: 'race',       circuitId: 'guadalajara'     },
  { round:  5, eventType: 'qualifying', circuitId: 'kyushu'          },
  { round:  5, eventType: 'race',       circuitId: 'kyushu'          },
  { round:  6, eventType: 'qualifying', circuitId: 'nairobi'         },
  { round:  6, eventType: 'race',       circuitId: 'nairobi'         },
  { round:  7, eventType: 'qualifying', circuitId: 'laeken'          },
  { round:  7, eventType: 'race',       circuitId: 'laeken'          },
  { round:  8, eventType: 'qualifying', circuitId: 'cotedazur'       },
  { round:  8, eventType: 'race',       circuitId: 'cotedazur'       },
  { round:  9, eventType: 'qualifying', circuitId: 'palermo'         },
  { round:  9, eventType: 'race',       circuitId: 'palermo'         },
  { round: 10, eventType: 'qualifying', circuitId: 'schwarzwald'     },
  { round: 10, eventType: 'race',       circuitId: 'schwarzwald'     },
  { round: 11, eventType: 'qualifying', circuitId: 'karlovyvary'     },
  { round: 11, eventType: 'race',       circuitId: 'karlovyvary'     },
  { round: 12, eventType: 'qualifying', circuitId: 'brookthorpe'     },
  { round: 12, eventType: 'race',       circuitId: 'brookthorpe'     },
  { round: 13, eventType: 'qualifying', circuitId: 'hamnkurs'        },
  { round: 13, eventType: 'race',       circuitId: 'hamnkurs'        },
  { round: 14, eventType: 'qualifying', circuitId: 'rovaniemi'       },
  { round: 14, eventType: 'race',       circuitId: 'rovaniemi'       },
  { round: 15, eventType: 'qualifying', circuitId: 'harbourfront'    },
  { round: 15, eventType: 'race',       circuitId: 'harbourfront'    },
  { round: 16, eventType: 'qualifying', circuitId: 'lacMeech'        },
  { round: 16, eventType: 'race',       circuitId: 'lacMeech'        },
  { round: 17, eventType: 'qualifying', circuitId: 'douglas'         },
  { round: 17, eventType: 'race',       circuitId: 'douglas'         },
  { round: 18, eventType: 'qualifying', circuitId: 'lahore'          },
  { round: 18, eventType: 'race',       circuitId: 'lahore'          },
  { round: 19, eventType: 'qualifying', circuitId: 'recife'          },
  { round: 19, eventType: 'race',       circuitId: 'recife'          },
  { round: 20, eventType: 'qualifying', circuitId: 'bushveld'        },
  { round: 20, eventType: 'race',       circuitId: 'bushveld'        },
];


// ─── Calendar epoch ───────────────────────────────────────────────────────────
// Day 0 of Season 1. All day offsets are computed from this date.
export const SEASON_1_START = '2026-04-19';
