// drivers.js — Driver data for Simple Motor Racing
//
// Two exports:
//
// DRIVER_POOL (IDs 0–23) — Season 1 starters. APPEND-ONLY; IDs are permanent.
//   Fields: id, firstName, lastName, nationality, gender, portraitIndex,
//           birthYear (≤ 1910 so driver is at least 20 in 1930), startTeam.
//   All stats (skill, consistency, aggression) are seeded from worldSeed + driverId
//   in worldstate.js — do not author them here.
//
// ROOKIE_NAME_POOL (indices 0+, corresponding to driverIds 24+) — pool of rookie
//   name/identity records. APPEND-ONLY and INDEX-BASED: index 0 = driverId 24,
//   index 1 = driverId 25, etc. Never reorder or delete entries.
//   Fields: firstName, lastName, nationality, gender, portraitIndex (where curated).
//
//   portraitIndex MUST remain a curated field — hand-matched to driver demographics
//   and sprite sheet appearances. NEVER derive it algorithmically. Entries without
//   a portraitIndex will fall back to coloured initials in the UI.

export const DRIVER_POOL = [

  // ── Hartwell Racing (Great Britain) ──────────────────────────────────────────
  {
    id: 0,
    firstName: 'Marco',        lastName: 'Alessi',
    nationality: 'italian',    gender: 'male',
    birthYear: 1900,           startTeam: 'hartwell',  portraitIndex: 0,
  },
  {
    id: 1,
    firstName: 'Eileen',       lastName: 'Burke',
    nationality: 'irish',      gender: 'female',
    birthYear: 1903,           startTeam: 'hartwell',  portraitIndex: 1,
  },

  // ── Flinders Racing Developments (Australia) ─────────────────────────────────
  {
    id: 2,
    firstName: 'Carlos',       lastName: 'Medina',
    nationality: 'spanish',    gender: 'male',
    birthYear: 1898,           startTeam: 'frd',       portraitIndex: 2,
  },
  {
    id: 3,
    firstName: 'Agnes',        lastName: 'Nolan',
    nationality: 'irish',      gender: 'female',
    birthYear: 1905,           startTeam: 'frd',       portraitIndex: 3,
  },

  // ── Officine Ferrosso (Italy) ─────────────────────────────────────────────────
  {
    id: 4,
    firstName: 'Hiroshi',      lastName: 'Abe',
    nationality: 'japanese',   gender: 'male',
    birthYear: 1895,           startTeam: 'ferrosso',  portraitIndex: 4,
  },
  {
    id: 5,
    firstName: 'Sofia',        lastName: 'Esposito',
    nationality: 'italian',    gender: 'female',
    birthYear: 1902,           startTeam: 'ferrosso',  portraitIndex: 5,
  },

  // ── Vettura Corse (Italy) ─────────────────────────────────────────────────────
  {
    id: 6,
    firstName: 'Alistair',     lastName: 'Quinn',
    nationality: 'irish',      gender: 'male',
    birthYear: 1899,           startTeam: 'vettura',   portraitIndex: 6,
  },
  {
    id: 7,
    firstName: 'Rajan',        lastName: 'Mehta',
    nationality: 'indian',     gender: 'male',
    birthYear: 1906,           startTeam: 'vettura',   portraitIndex: 7,
  },

  // ── Kaiserwerke GP (Germany) ──────────────────────────────────────────────────
  {
    id: 8,
    firstName: 'Teresa',       lastName: 'Morales',
    nationality: 'spanish',    gender: 'female',
    birthYear: 1893,           startTeam: 'kaiserwerke', portraitIndex: 8,
  },
  {
    id: 9,
    firstName: 'Jiaming',      lastName: 'Wu',
    nationality: 'chinese',    gender: 'male',
    birthYear: 1901,           startTeam: 'kaiserwerke', portraitIndex: 9,
  },

  // ── Écurie Mistral (France) ───────────────────────────────────────────────────
  {
    id: 10,
    firstName: 'Amara',        lastName: 'Diallo',
    nationality: 'senegalese', gender: 'female',
    birthYear: 1897,           startTeam: 'mistral',   portraitIndex: 10,
  },
  {
    id: 11,
    firstName: 'Giacomo',      lastName: 'Rossi',
    nationality: 'italian',    gender: 'male',
    birthYear: 1904,           startTeam: 'mistral',   portraitIndex: 11,
  },

  // ── Alpenring Motorsport (Austria) ────────────────────────────────────────────
  {
    id: 12,
    firstName: 'Andrei',       lastName: 'Horak',
    nationality: 'czech',      gender: 'male',
    birthYear: 1896,           startTeam: 'alpenring', portraitIndex: 12,
  },
  {
    id: 13,
    firstName: 'Violet',       lastName: 'Ashton',
    nationality: 'british',    gender: 'female',
    birthYear: 1908,           startTeam: 'alpenring', portraitIndex: 13,
  },

  // ── Delta Bravo Racing (Great Britain) ───────────────────────────────────────
  {
    id: 14,
    firstName: 'Roberto',      lastName: 'Vargas',
    nationality: 'argentinian', gender: 'male',
    birthYear: 1900,           startTeam: 'deltaBravo', portraitIndex: 14,
  },
  {
    id: 15,
    firstName: 'Marta',        lastName: 'Szabo',
    nationality: 'hungarian',  gender: 'female',
    birthYear: 1907,           startTeam: 'deltaBravo', portraitIndex: 15,
  },

  // ── Eaglecrest Racing (USA) ───────────────────────────────────────────────────
  {
    id: 16,
    firstName: 'Erik',         lastName: 'Lindqvist',
    nationality: 'swedish',    gender: 'male',
    birthYear: 1894,           startTeam: 'eaglecrest', portraitIndex: 16,
  },
  {
    id: 17,
    firstName: 'Leila',        lastName: 'Mansour',
    nationality: 'moroccan',   gender: 'female',
    birthYear: 1903,           startTeam: 'eaglecrest', portraitIndex: 17,
  },

  // ── Sakura Grand Prix (Japan) ─────────────────────────────────────────────────
  {
    id: 18,
    firstName: 'Nikos',        lastName: 'Stavros',
    nationality: 'greek',      gender: 'male',
    birthYear: 1901,           startTeam: 'sakura',    portraitIndex: 18,
  },
  {
    id: 19,
    firstName: 'Fiona',        lastName: 'Gallagher',
    nationality: 'irish',      gender: 'female',
    birthYear: 1906,           startTeam: 'sakura',    portraitIndex: 19,
  },

  // ── Santos Automotive (Brazil) ────────────────────────────────────────────────
  {
    id: 20,
    firstName: 'Kwame',        lastName: 'Asante',
    nationality: 'ghanaian',   gender: 'male',
    birthYear: 1898,           startTeam: 'santos',    portraitIndex: 20,
  },
  {
    id: 21,
    firstName: 'Yuki',         lastName: 'Hashimoto',
    nationality: 'japanese',   gender: 'female',
    birthYear: 1905,           startTeam: 'santos',    portraitIndex: 21,
  },

  // ── O'Connell Racing (Ireland) ────────────────────────────────────────────────
  {
    id: 22,
    firstName: 'Hassan',       lastName: 'Khalil',
    nationality: 'egyptian',   gender: 'male',
    birthYear: 1896,           startTeam: 'oconnell',  portraitIndex: 22,
  },
  {
    id: 23,
    firstName: 'Beatrice',     lastName: 'Forde',
    nationality: 'british',    gender: 'female',
    birthYear: 1909,           startTeam: 'oconnell',  portraitIndex: 23,
  },

  // add new S1 starter entries below this line — always append, never reorder

];

// ─── Rookie name pool ─────────────────────────────────────────────────────────
// Index 0 = driverId 24, index 1 = driverId 25, etc.
// APPEND-ONLY. Never reorder or delete — indices are permanent.
// portraitIndex is hand-curated to match demographics; never derive algorithmically.

export const ROOKIE_NAME_POOL = [
  { firstName: 'Diego',      lastName: 'Montoya',  nationality: 'colombian',     gender: 'male',   portraitIndex: 24 },
  { firstName: 'Isabelle',   lastName: 'Fontaine', nationality: 'french',        gender: 'female', portraitIndex: 25 },
  { firstName: 'Cedric',     lastName: 'Holt',     nationality: 'british',       gender: 'male',   portraitIndex: 26 },
  { firstName: 'Adaeze',     lastName: 'Okafor',   nationality: 'nigerian',      gender: 'female', portraitIndex: 27 },
  { firstName: 'Luis',       lastName: 'Reyes',    nationality: 'mexican',       gender: 'male',   portraitIndex: 28 },
  { firstName: 'Nadia',      lastName: 'Farouk',   nationality: 'egyptian',      gender: 'female', portraitIndex: 29 },
  { firstName: 'Douglas',    lastName: 'Walsh',    nationality: 'british',       gender: 'male',   portraitIndex: 30 },
  { firstName: 'Valentina',  lastName: 'Cruz',     nationality: 'argentinian',   gender: 'female', portraitIndex: 31 },
  { firstName: 'Henry',      lastName: 'Lafleur',  nationality: 'canadian',      gender: 'male',   portraitIndex: 32 },
  { firstName: 'Marta',      lastName: 'Novak',    nationality: 'czech',         gender: 'female', portraitIndex: 33 },
  { firstName: 'Paavo',      lastName: 'Maki',     nationality: 'finnish',       gender: 'male',   portraitIndex: 34 },
  { firstName: 'Ingrid',     lastName: 'Dahl',     nationality: 'norwegian',     gender: 'female', portraitIndex: 35 },
  { firstName: 'Istvan',     lastName: 'Fekete',   nationality: 'hungarian',     gender: 'male',   portraitIndex: 36 },
  { firstName: 'Ana',        lastName: 'Monteiro', nationality: 'portuguese',    gender: 'female', portraitIndex: 37 },
  { firstName: 'Wei',        lastName: 'Chen',     nationality: 'chinese',       gender: 'male',   portraitIndex: 38 },
  { firstName: 'Priya',      lastName: 'Sharma',   nationality: 'indian',        gender: 'female', portraitIndex: 39 },
  { firstName: 'Jack',       lastName: 'Galloway', nationality: 'new zealander', gender: 'male',   portraitIndex: 40 },
  { firstName: 'Karen',      lastName: 'Holm',     nationality: 'danish',        gender: 'female', portraitIndex: 41 },
  { firstName: 'Roy',        lastName: 'Sullivan', nationality: 'american',      gender: 'male',   portraitIndex: 42 },
  { firstName: 'Sylvia',     lastName: 'Grant',    nationality: 'british',       gender: 'female', portraitIndex: 43 },
  { firstName: 'Marco',      lastName: 'Grassi',   nationality: 'italian',       gender: 'male',   portraitIndex: 44 },
  { firstName: 'Elsa',       lastName: 'Werner',   nationality: 'german',        gender: 'female', portraitIndex: 45 },
  { firstName: 'Paul',       lastName: 'Lebrun',   nationality: 'french',        gender: 'male',   portraitIndex: 46 },
  { firstName: 'Sofia',      lastName: 'Lima',     nationality: 'brazilian',     gender: 'female', portraitIndex: 47 },
  { firstName: 'Thomas',     lastName: 'Whitfield',nationality: 'british',       gender: 'male'   },
  { firstName: 'Simone',     lastName: 'Picart',   nationality: 'french',        gender: 'female' },
  { firstName: 'Klaus',      lastName: 'Becker',   nationality: 'german',        gender: 'male'   },
  { firstName: 'Giulia',     lastName: 'Ferrara',  nationality: 'italian',       gender: 'female' },
  { firstName: 'Felipe',     lastName: 'Ramos',    nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Takashi',    lastName: 'Kato',     nationality: 'japanese',      gender: 'male'   },
  { firstName: 'Astrid',     lastName: 'Lund',     nationality: 'swedish',       gender: 'female' },
  { firstName: 'Rafael',     lastName: 'Torres',   nationality: 'spanish',       gender: 'male'   },
  { firstName: 'Karen',      lastName: 'Nash',     nationality: 'australian',    gender: 'female' },
  { firstName: 'Aaron',      lastName: 'Hart',     nationality: 'american',      gender: 'male'   },
  { firstName: 'Yuki',       lastName: 'Tanaka',   nationality: 'japanese',      gender: 'female' },
  { firstName: 'Lars',       lastName: 'Nilsson',  nationality: 'swedish',       gender: 'male'   },
  { firstName: 'Ana',        lastName: 'Vieira',   nationality: 'brazilian',     gender: 'female' },
  { firstName: 'Stefan',     lastName: 'Kraus',    nationality: 'german',        gender: 'male'   },
  { firstName: 'Carmen',     lastName: 'Flores',   nationality: 'spanish',       gender: 'female' },
  { firstName: 'Shane',      lastName: 'Webb',     nationality: 'australian',    gender: 'male'   },
  { firstName: 'Nathalie',   lastName: 'Blanc',    nationality: 'french',        gender: 'female' },
  { firstName: 'Mikko',      lastName: 'Laine',    nationality: 'finnish',       gender: 'male'   },
  { firstName: 'Isabel',     lastName: 'Mora',     nationality: 'spanish',       gender: 'female' },
  { firstName: 'Jeroen',     lastName: 'Kuiper',   nationality: 'dutch',         gender: 'male'   },
  { firstName: 'Riikka',     lastName: 'Lehto',    nationality: 'finnish',       gender: 'female' },
  { firstName: 'Thiago',     lastName: 'Lima',     nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Chiara',     lastName: 'Russo',    nationality: 'italian',       gender: 'female' },
  { firstName: 'Edward',     lastName: 'Barker',   nationality: 'british',       gender: 'male'   },
  { firstName: 'Sabine',     lastName: 'Ritter',   nationality: 'german',        gender: 'female' },
  { firstName: 'Lorenzo',    lastName: 'Mazza',    nationality: 'italian',       gender: 'male'   },
  { firstName: 'Ashley',     lastName: 'Moore',    nationality: 'american',      gender: 'female' },
  { firstName: 'Kenji',      lastName: 'Hayashi',  nationality: 'japanese',      gender: 'male'   },
  { firstName: 'Eero',       lastName: 'Makinen',  nationality: 'finnish',       gender: 'male'   },
  { firstName: 'Valentina',  lastName: 'Rossi',    nationality: 'italian',       gender: 'female' },
  { firstName: 'Antoine',    lastName: 'Moreau',   nationality: 'french',        gender: 'male'   },
  { firstName: 'Michelle',   lastName: 'Bird',     nationality: 'australian',    gender: 'female' },
  { firstName: 'Rodrigo',    lastName: 'Pinto',    nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Ingrid',     lastName: 'Strand',   nationality: 'norwegian',     gender: 'female' },
  { firstName: 'Miguel',     lastName: 'Vargas',   nationality: 'spanish',       gender: 'male'   },
  { firstName: 'Akiko',      lastName: 'Watanabe', nationality: 'japanese',      gender: 'female' },
  { firstName: 'Craig',      lastName: 'Fox',      nationality: 'australian',    gender: 'male'   },
  { firstName: 'Elena',      lastName: 'Rubio',    nationality: 'spanish',       gender: 'female' },
  { firstName: 'Tyler',      lastName: 'Woods',    nationality: 'american',      gender: 'male'   },
  { firstName: 'Anke',       lastName: 'Vogel',    nationality: 'german',        gender: 'female' },
  { firstName: 'Matteo',     lastName: 'Bruno',    nationality: 'italian',       gender: 'male'   },
  { firstName: 'Beatriz',    lastName: 'Faria',    nationality: 'portuguese',    gender: 'female' },
  { firstName: 'Michael',    lastName: 'Braun',    nationality: 'german',        gender: 'male'   },
  { firstName: 'Karin',      lastName: 'Sund',     nationality: 'swedish',       gender: 'female' },
  { firstName: 'Jean',       lastName: 'Aubert',   nationality: 'french',        gender: 'male'   },
  { firstName: 'Naomi',      lastName: 'Kobayashi',nationality: 'japanese',      gender: 'female' },
  { firstName: 'George',     lastName: 'Croft',    nationality: 'british',       gender: 'male'   },
  { firstName: 'Mariana',    lastName: 'Belo',     nationality: 'brazilian',     gender: 'female' },
  { firstName: 'Ryo',        lastName: 'Sato',     nationality: 'japanese',      gender: 'male'   },
  { firstName: 'Dorothy',    lastName: 'Shaw',     nationality: 'british',       gender: 'female' },
  { firstName: 'Blake',      lastName: 'Stone',    nationality: 'american',      gender: 'male'   },
  { firstName: 'Yvette',     lastName: 'Aurel',    nationality: 'french',        gender: 'female' },
  { firstName: 'Roberto',    lastName: 'Vitale',   nationality: 'italian',       gender: 'male'   },
  { firstName: 'Sunita',     lastName: 'Nair',     nationality: 'indian',        gender: 'female' },
  { firstName: 'Piotr',      lastName: 'Nowak',    nationality: 'polish',        gender: 'male'   },
  { firstName: 'Kofi',       lastName: 'Asante',   nationality: 'ghanaian',      gender: 'male'   },
  { firstName: 'Lucia',      lastName: 'Vidal',    nationality: 'spanish',       gender: 'female' },
  { firstName: 'Emilio',     lastName: 'Ramirez',  nationality: 'mexican',       gender: 'male'   },
  { firstName: 'Sigrid',     lastName: 'Berg',     nationality: 'norwegian',     gender: 'female' },
  { firstName: 'Franco',     lastName: 'Gallo',    nationality: 'italian',       gender: 'male'   },
  { firstName: 'Sari',       lastName: 'Niemi',    nationality: 'finnish',       gender: 'female' },
  { firstName: 'Gustavo',    lastName: 'Alves',    nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Fatou',      lastName: 'Diallo',   nationality: 'senegalese',    gender: 'female' },
  { firstName: 'Naoki',      lastName: 'Yamada',   nationality: 'japanese',      gender: 'male'   },
  { firstName: 'Monika',     lastName: 'Fischer',  nationality: 'german',        gender: 'female' },
  { firstName: 'William',    lastName: 'Moss',     nationality: 'british',       gender: 'male'   },
  { firstName: 'Aminata',    lastName: 'Toure',    nationality: 'senegalese',    gender: 'female' },
  { firstName: 'Derek',      lastName: 'Cole',     nationality: 'american',      gender: 'male'   },
  { firstName: 'Francisca',  lastName: 'Pinto',    nationality: 'portuguese',    gender: 'female' },
  { firstName: 'Gabriel',    lastName: 'Nunes',    nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Emi',        lastName: 'Suzuki',   nationality: 'japanese',      gender: 'female' },
  { firstName: 'Andras',     lastName: 'Fekete',   nationality: 'hungarian',     gender: 'male'   },
  { firstName: 'Marjolein',  lastName: 'Bos',      nationality: 'dutch',         gender: 'female' },
  { firstName: 'Vikram',     lastName: 'Rao',      nationality: 'indian',        gender: 'male'   },
  { firstName: 'Nicole',     lastName: 'Dale',     nationality: 'australian',    gender: 'female' },
  { firstName: 'Alain',      lastName: 'Renard',   nationality: 'french',        gender: 'male'   },
  { firstName: 'Olga',       lastName: 'Sorokina', nationality: 'czech',         gender: 'female' },
  { firstName: 'Grant',      lastName: 'Lowe',     nationality: 'australian',    gender: 'male'   },
  { firstName: 'Luciana',    lastName: 'Ruiz',     nationality: 'argentinian',   gender: 'female' },
  { firstName: 'Wolfgang',   lastName: 'Koch',     nationality: 'german',        gender: 'male'   },
  { firstName: 'Marta',      lastName: 'Blanco',   nationality: 'spanish',       gender: 'female' },
  { firstName: 'Femi',       lastName: 'Adeyemi',  nationality: 'nigerian',      gender: 'male'   },
  { firstName: 'Haruka',     lastName: 'Ito',      nationality: 'japanese',      gender: 'female' },
  { firstName: 'Sanjay',     lastName: 'Kapoor',   nationality: 'indian',        gender: 'male'   },
  { firstName: 'Pilar',      lastName: 'Cano',     nationality: 'spanish',       gender: 'female' },
  { firstName: 'Bjorn',      lastName: 'Strand',   nationality: 'swedish',       gender: 'male'   },
  { firstName: 'Ngozi',      lastName: 'Obi',      nationality: 'nigerian',      gender: 'female' },
  { firstName: 'Lucas',      lastName: 'Silva',    nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Tracey',     lastName: 'Swift',    nationality: 'australian',    gender: 'female' },
  { firstName: 'Javier',     lastName: 'Gil',      nationality: 'spanish',       gender: 'male'   },
  { firstName: 'Claudia',    lastName: 'Berger',   nationality: 'german',        gender: 'female' },
  { firstName: 'Arthur',     lastName: 'Reid',     nationality: 'british',       gender: 'male'   },
  { firstName: 'Kofi',       lastName: 'Mensah',   nationality: 'ghanaian',      gender: 'male'   },
  { firstName: 'Carla',      lastName: 'Ferreira', nationality: 'portuguese',    gender: 'female' },
  { firstName: 'Tibor',      lastName: 'Varga',    nationality: 'hungarian',     gender: 'male'   },
  { firstName: 'Heli',       lastName: 'Aho',      nationality: 'finnish',       gender: 'female' },
  { firstName: 'Daniele',    lastName: 'Moretti',  nationality: 'italian',       gender: 'male'   },
  { firstName: 'Morgan',     lastName: 'Scott',    nationality: 'american',      gender: 'female' },
  { firstName: 'Kohei',      lastName: 'Inoue',    nationality: 'japanese',      gender: 'male'   },
  { firstName: 'Hanneke',    lastName: 'Visser',   nationality: 'dutch',         gender: 'female' },
  { firstName: 'Wade',       lastName: 'Pierce',   nationality: 'american',      gender: 'male'   },
  { firstName: 'Inge',       lastName: 'Hartmann', nationality: 'german',        gender: 'female' },
  { firstName: 'Eduardo',    lastName: 'Rocha',    nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Greta',      lastName: 'Nyman',    nationality: 'swedish',       gender: 'female' },
  { firstName: 'Marek',      lastName: 'Novak',    nationality: 'czech',         gender: 'male'   },
  { firstName: 'Divya',      lastName: 'Menon',    nationality: 'indian',        gender: 'female' },
  { firstName: 'Glenn',      lastName: 'Ward',     nationality: 'australian',    gender: 'male'   },
  { firstName: 'Sylvie',     lastName: 'Morel',    nationality: 'french',        gender: 'female' },
  { firstName: 'Pietro',     lastName: 'Serra',    nationality: 'italian',       gender: 'male'   },
  { firstName: 'Amara',      lastName: 'Diagne',   nationality: 'senegalese',    gender: 'female' },
  { firstName: 'Gerhard',    lastName: 'Stein',    nationality: 'german',        gender: 'male'   },
  { firstName: 'Colette',    lastName: 'Faure',    nationality: 'french',        gender: 'female' },
  { firstName: 'Brett',      lastName: 'Burns',    nationality: 'australian',    gender: 'male'   },
  { firstName: 'Agnieszka',  lastName: 'Witek',    nationality: 'polish',        gender: 'female' },
  { firstName: 'Raul',       lastName: 'Navarro',  nationality: 'mexican',       gender: 'male'   },
  { firstName: 'Irene',      lastName: 'Papadaki', nationality: 'greek',         gender: 'female' },
  { firstName: 'Nicolas',    lastName: 'Garnier',  nationality: 'french',        gender: 'male'   },
  { firstName: 'Madison',    lastName: 'King',     nationality: 'american',      gender: 'female' },
  { firstName: 'Enrico',     lastName: 'Amato',    nationality: 'italian',       gender: 'male'   },
  { firstName: 'Meena',      lastName: 'Pillai',   nationality: 'indian',        gender: 'female' },
  { firstName: 'Frank',      lastName: 'Smit',     nationality: 'dutch',         gender: 'male'   },
  { firstName: 'Camille',    lastName: 'Roux',     nationality: 'french',        gender: 'female' },
  { firstName: 'Arun',       lastName: 'Krishnan', nationality: 'indian',        gender: 'male'   },
  { firstName: 'Patricia',   lastName: 'Holt',     nationality: 'british',       gender: 'female' },
  { firstName: 'Tunde',      lastName: 'Bakare',   nationality: 'nigerian',      gender: 'male'   },
  { firstName: 'Akosua',     lastName: 'Amponsah', nationality: 'ghanaian',      gender: 'female' },
  { firstName: 'Miroslav',   lastName: 'Horak',    nationality: 'czech',         gender: 'male'   },
  { firstName: 'Monique',    lastName: 'Dupont',   nationality: 'french',        gender: 'female' },
  { firstName: 'Kyle',       lastName: 'Marsh',    nationality: 'american',      gender: 'male'   },
  { firstName: 'Daniela',    lastName: 'Pires',    nationality: 'portuguese',    gender: 'female' },
  { firstName: 'Taiki',      lastName: 'Ogawa',    nationality: 'japanese',      gender: 'male'   },
  { firstName: 'Lena',       lastName: 'Baum',     nationality: 'german',        gender: 'female' },
  { firstName: 'Santiago',   lastName: 'Perez',    nationality: 'colombian',     gender: 'male'   },
  { firstName: 'Anja',       lastName: 'DeVries',  nationality: 'dutch',         gender: 'female' },
  { firstName: 'Peter',      lastName: 'Knox',     nationality: 'british',       gender: 'male'   },
  { firstName: 'Fernanda',   lastName: 'Melo',     nationality: 'brazilian',     gender: 'female' },
  { firstName: 'Antti',      lastName: 'Kari',     nationality: 'finnish',       gender: 'male'   },
  { firstName: 'Paloma',     lastName: 'Vega',     nationality: 'spanish',       gender: 'female' },
  { firstName: 'Emeka',      lastName: 'Okafor',   nationality: 'nigerian',      gender: 'male'   },
  { firstName: 'Birgitta',   lastName: 'Ek',       nationality: 'swedish',       gender: 'female' },
  { firstName: 'Robert',     lastName: 'Birch',    nationality: 'british',       gender: 'male'   },
  { firstName: 'Mio',        lastName: 'Kimura',   nationality: 'japanese',      gender: 'female' },
  { firstName: 'Dieter',     lastName: 'Wolf',     nationality: 'german',        gender: 'male'   },
  { firstName: 'Rocio',      lastName: 'Serrano',  nationality: 'spanish',       gender: 'female' },
  { firstName: 'Bruno',      lastName: 'Rocha',    nationality: 'brazilian',     gender: 'male'   },
  { firstName: 'Hannelore',  lastName: 'Muller',   nationality: 'german',        gender: 'female' },
  { firstName: 'Knut',       lastName: 'Odegard',  nationality: 'norwegian',     gender: 'male'   },
  { firstName: 'Luciana',    lastName: 'Gomes',    nationality: 'brazilian',     gender: 'female' },
  { firstName: 'David',      lastName: 'Fleming',  nationality: 'british',       gender: 'male'   },
  { firstName: 'Sachiko',    lastName: 'Fujii',    nationality: 'japanese',      gender: 'female' },
  { firstName: 'Clint',      lastName: 'Lawson',   nationality: 'american',      gender: 'male'   },
  { firstName: 'Beatrix',    lastName: 'Sandor',   nationality: 'hungarian',     gender: 'female' },
  { firstName: 'Francois',   lastName: 'Petit',    nationality: 'french',        gender: 'male'   },
  { firstName: 'Amina',      lastName: 'Diallo',   nationality: 'moroccan',      gender: 'female' },
  { firstName: 'Pieter',     lastName: 'Claes',    nationality: 'belgian',       gender: 'male'   },
  { firstName: 'Yemi',       lastName: 'Adebayo',  nationality: 'nigerian',      gender: 'female' },
  { firstName: 'Richard',    lastName: 'Drew',     nationality: 'british',       gender: 'male'   },
  { firstName: 'Katarzyna',  lastName: 'Kowal',    nationality: 'polish',        gender: 'female' },
  { firstName: 'Hiroki',     lastName: 'Nakamura', nationality: 'japanese',      gender: 'male'   },
  { firstName: 'Birte',      lastName: 'Holm',     nationality: 'danish',        gender: 'female' },
  { firstName: 'Oscar',      lastName: 'Herrera',  nationality: 'mexican',       gender: 'male'   },
  { firstName: 'Renata',     lastName: 'Almeida',  nationality: 'brazilian',     gender: 'female' },
  { firstName: 'Tobias',     lastName: 'Jung',     nationality: 'german',        gender: 'male'   },
  { firstName: 'Aoi',        lastName: 'Nishida',  nationality: 'japanese',      gender: 'female' },
  { firstName: 'Charles',    lastName: 'Orr',      nationality: 'british',       gender: 'male'   },
  { firstName: 'Ama',        lastName: 'Boateng',  nationality: 'ghanaian',      gender: 'female' },
  { firstName: 'Lance',      lastName: 'Drury',    nationality: 'american',      gender: 'male'   },
  { firstName: 'Ursula',     lastName: 'Brandt',   nationality: 'german',        gender: 'female' },
  { firstName: 'Andres',     lastName: 'Molina',   nationality: 'colombian',     gender: 'male'   },
  { firstName: 'Silvia',     lastName: 'Riva',     nationality: 'italian',       gender: 'female' },
  { firstName: 'Mats',       lastName: 'Lindqvist',nationality: 'swedish',       gender: 'male'   },
  { firstName: 'Pooja',      lastName: 'Iyer',     nationality: 'indian',        gender: 'female' },
  { firstName: 'Wayne',      lastName: 'Frost',    nationality: 'australian',    gender: 'male'   },
  { firstName: 'Adriana',    lastName: 'Souza',    nationality: 'brazilian',     gender: 'female' },
  { firstName: 'Stig',       lastName: 'Andersen', nationality: 'danish',        gender: 'male'   },
  { firstName: 'Monica',     lastName: 'Leone',    nationality: 'italian',       gender: 'female' },
  { firstName: 'Nikhil',     lastName: 'Bhat',     nationality: 'indian',        gender: 'male'   },
  { firstName: 'Elsa',       lastName: 'Lindgren', nationality: 'swedish',       gender: 'female' },
  { firstName: 'Sergio',     lastName: 'Palma',    nationality: 'italian',       gender: 'male'   },
  { firstName: 'Taylor',     lastName: 'Reed',     nationality: 'american',      gender: 'female' },
  { firstName: 'Arne',       lastName: 'Bakke',    nationality: 'norwegian',     gender: 'male'   },
  { firstName: 'Brigitte',   lastName: 'Huber',    nationality: 'austrian',      gender: 'female' },
  { firstName: 'Alberto',    lastName: 'Cruz',     nationality: 'mexican',       gender: 'male'   },
  { firstName: 'Abena',      lastName: 'Ofori',    nationality: 'ghanaian',      gender: 'female' },
  { firstName: 'Jack',       lastName: 'Gould',    nationality: 'new zealander', gender: 'male'   },
  { firstName: 'Nadia',      lastName: 'Moussa',   nationality: 'moroccan',      gender: 'female' },
  { firstName: 'Ville',      lastName: 'Heino',    nationality: 'finnish',       gender: 'male'   },
  { firstName: 'Joanna',     lastName: 'Mucha',    nationality: 'polish',        gender: 'female' },
  { firstName: 'Pedro',      lastName: 'Sousa',    nationality: 'portuguese',    gender: 'male'   },
  { firstName: 'Sakura',     lastName: 'Goto',     nationality: 'japanese',      gender: 'female' },
  { firstName: 'Marc',       lastName: 'Jansen',   nationality: 'belgian',       gender: 'male'   },
  { firstName: 'Chidi',      lastName: 'Okeke',    nationality: 'nigerian',      gender: 'male'   },
  { firstName: 'Helga',      lastName: 'Aas',      nationality: 'norwegian',     gender: 'female' },
  { firstName: 'Claudio',    lastName: 'Vargas',   nationality: 'argentinian',   gender: 'male'   },
  { firstName: 'Neha',       lastName: 'Joshi',    nationality: 'indian',        gender: 'female' },
  { firstName: 'Philip',     lastName: 'Grant',    nationality: 'british',       gender: 'male'   },
  { firstName: 'Viviane',    lastName: 'Lopes',    nationality: 'brazilian',     gender: 'female' },
  { firstName: 'Gunnar',     lastName: 'Vik',      nationality: 'norwegian',     gender: 'male'   },
  { firstName: 'Rosa',       lastName: 'Medina',   nationality: 'spanish',       gender: 'female' },
  { firstName: 'Shota',      lastName: 'Miyamoto', nationality: 'japanese',      gender: 'male'   },

  // add new rookie entries below this line — always append, never reorder
];
